# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wsb < Formula
  desc "wsb binary distribution using homebrew."
  homepage "https://github.com/regel/homebrew-tap"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/regel/wsb/releases/download/v0.1.9/wsb_0.1.9_darwin_amd64.tar.gz"
      sha256 "4709e15949b3cac5603f8a9fef5330e0187735beaf3dd2b7e0b092a9d04ef26a"

      def install
        bin.install "wsb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/regel/wsb/releases/download/v0.1.9/wsb_0.1.9_darwin_arm64.tar.gz"
      sha256 "eebabf685af852ccbbecbfa748b22041893fd3c00bf27afe4e0f9f8f2c3f860c"

      def install
        bin.install "wsb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/regel/wsb/releases/download/v0.1.9/wsb_0.1.9_linux_amd64.tar.gz"
      sha256 "e7dda397fafc116129485b1ac9b5b76c5772ff7970ff36077c181492250e09cb"

      def install
        bin.install "wsb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/regel/wsb/releases/download/v0.1.9/wsb_0.1.9_linux_arm64.tar.gz"
      sha256 "80c42fd2edf7e51d02e775389b86743f6bed6cd523470329e26b7a2b3a91cc74"

      def install
        bin.install "wsb"
      end
    end
  end
end
